package View;

import Connection.Conexao;
import Control.ProdutoControl;
import Model.Produto;
import java.sql.*;
/*import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;*/
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class TelaProduto extends javax.swing.JFrame {
    ProdutoControl control;
     
    public TelaProduto() {
        initComponents();
        
        /* Ordenamento da Tabela
        DefaultTableModel modelo = (DefaultTableModel) eTab.getModel();
        eTab.setRowSorter(new TableRowSorter(modelo));
        eTab.setAutocreateRow(true);*/
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // instancia o controle
        control  = new ProdutoControl(this);
        // exibir a lista na tabela
        exibirNaTab(control.selecionarTodos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eCod = new javax.swing.JTextField();
        eNome = new javax.swing.JTextField();
        eQtd = new javax.swing.JTextField();
        eEst = new javax.swing.JTextField();
        ePrec = new javax.swing.JTextField();
        eIncluir = new javax.swing.JButton();
        eAtualizar = new javax.swing.JButton();
        eDeletar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eTab = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eLimpar = new javax.swing.JButton();
        eExibir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(635, 460));
        setResizable(false);

        eCod.setEditable(false);
        eCod.setBackground(new java.awt.Color(204, 204, 204));
        eCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCodActionPerformed(evt);
            }
        });

        eEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eEstActionPerformed(evt);
            }
        });

        eIncluir.setText("Incluir");
        eIncluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eIncluirActionPerformed(evt);
            }
        });

        eAtualizar.setText("Atualizar");
        eAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eAtualizarActionPerformed(evt);
            }
        });

        eDeletar.setText("Deletar");
        eDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eDeletarActionPerformed(evt);
            }
        });

        eTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Qtd. Minima", "Estoque Atual", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        eTab.getTableHeader().setReorderingAllowed(false);
        eTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(eTab);
        if (eTab.getColumnModel().getColumnCount() > 0) {
            eTab.getColumnModel().getColumn(0).setMinWidth(60);
            eTab.getColumnModel().getColumn(0).setPreferredWidth(60);
            eTab.getColumnModel().getColumn(0).setMaxWidth(60);
            eTab.getColumnModel().getColumn(2).setMinWidth(60);
            eTab.getColumnModel().getColumn(2).setPreferredWidth(60);
            eTab.getColumnModel().getColumn(2).setMaxWidth(60);
            eTab.getColumnModel().getColumn(3).setMinWidth(60);
            eTab.getColumnModel().getColumn(3).setPreferredWidth(60);
            eTab.getColumnModel().getColumn(3).setMaxWidth(60);
            eTab.getColumnModel().getColumn(4).setMinWidth(60);
            eTab.getColumnModel().getColumn(4).setPreferredWidth(60);
            eTab.getColumnModel().getColumn(4).setMaxWidth(60);
        }

        jLabel1.setText("Codigo");

        jLabel2.setText("Nome");

        jLabel3.setText("Qtd. Mínima");

        jLabel4.setText("Estoque");

        jLabel5.setText("Preço");

        eLimpar.setText("Limpar Formulario");
        eLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eLimparActionPerformed(evt);
            }
        });

        eExibir.setText("ExibirTodos os Produtos");
        eExibir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eExibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eExibirActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos3.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(eCod, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(eNome)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(eQtd, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(eEst, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ePrec, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(eIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(eAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ePrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(eEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eIncluir)))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eDeletar)
                    .addComponent(eExibir)
                    .addComponent(eAtualizar)
                    .addComponent(eLimpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Eventos
    private void eCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eCodActionPerformed

    private void eIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eIncluirActionPerformed
        if(!"".equals(eNome.getText())){
            if(control.inserir()){
                // exibir a lista na tabela
                exibirNaTab(control.selecionarTodos());
                limparForm();
                JOptionPane.showMessageDialog(this, "Produto Incluido");
            }
            else{
                JOptionPane.showMessageDialog(this, "Falha Inserção");
            }
        }
        else JOptionPane.showMessageDialog(this, "Descreva o Nome do Produto");
    }//GEN-LAST:event_eIncluirActionPerformed

    private void eAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eAtualizarActionPerformed
        if(!"".equals(eCod.getText()) ){
            if(control.atualizar()){
                exibirNaTab(control.selecionarTodos());
                limparForm();
                JOptionPane.showMessageDialog(this, "Produto Atualizado");
            }
            else{
                JOptionPane.showMessageDialog(this, "Falha Atualização");
            }
            
        }
        else JOptionPane.showMessageDialog(this, "Selecione um Produto na Tabela");
    }//GEN-LAST:event_eAtualizarActionPerformed

    private void eTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eTabMouseClicked
        selecionarDaTab();
        
    }//GEN-LAST:event_eTabMouseClicked

    private void eDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eDeletarActionPerformed
        if(!"".equals(eCod.getText())){
            if(JOptionPane.showConfirmDialog(this, "Deseja Deletar esse Produto?") == 0){
                if(control.deletar()){
                    exibirNaTab(control.selecionarTodos());
                    limparForm();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Falha ao Deletar Produto");
                }
            }
        }
        else JOptionPane.showMessageDialog(this, "Selecione um Produto na Tabela");
    }//GEN-LAST:event_eDeletarActionPerformed

    private void eLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eLimparActionPerformed
        limparForm();
    }//GEN-LAST:event_eLimparActionPerformed

    private void eExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eExibirActionPerformed
        exibirNaTab(control.selecionarTodos());
    }//GEN-LAST:event_eExibirActionPerformed

    private void eEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eEstActionPerformed

    // Metodos
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProduto().setVisible(true);
            }
        });
    }
    
    // le os dados do formulario e retorna um objeto Produto
    public Produto lerForm(){
        Produto f = new Produto();
        f.setCod( Integer.valueOf("0" +eCod.getText()) );
        f.setNome(eNome.getText() );
        f.setQtda( Integer.valueOf(eQtd.getText()) );
        f.setEstoque( Integer.valueOf(eEst.getText()) );
        f.setPreco( Float.valueOf(ePrec.getText()) );
        
        return f;
    }
    
    // exibe um dado objeto Produto no formulario
    public void exibirNoForm(Produto f){
        eCod.setText( Integer.toString(f.getCod()) );
        eNome.setText( f.getNome() );
        eQtd.setText( Integer.toString(f.getQtda()) );
        eEst.setText( Integer.toString(f.getEstoque()) );
        ePrec.setText( Float.toString(f.getPreco()) );
      
    }
    
    //
    public void selecionarDaTab(){
        int linha = eTab.getSelectedRow();
        eCod.setText(eTab.getModel().getValueAt(linha, 0).toString());
        eNome.setText(eTab.getModel().getValueAt(linha, 1).toString());
        eQtd.setText(eTab.getModel().getValueAt(linha, 2).toString());
        eEst.setText(eTab.getModel().getValueAt(linha, 3).toString());
        ePrec.setText(eTab.getModel().getValueAt(linha, 4).toString());
    }

    // exibe uma dada lista de objetos Produto na tabela
    public void exibirNaTab(List<Produto> l){
        DefaultTableModel tabMod = (DefaultTableModel) eTab.getModel();
        tabMod.setRowCount(0);
        
        for(Produto f : l){
            String[] row = new String[5];  
            row[0] = (String.valueOf(f.getCod()));
            row[1] = f.getNome();
            row[2] = (String.valueOf(f.getQtda()));
            row[3] = (String.valueOf(f.getEstoque()));
            row[4] = (String.valueOf(f.getPreco()));
            
            tabMod.addRow(row);
        }
    }
    
    public void limparForm(){
        eCod.setText( "" );
        eNome.setText( "" );
        eQtd.setText( "" );
        eEst.setText( "" );
        ePrec.setText( "" );
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eAtualizar;
    private javax.swing.JTextField eCod;
    private javax.swing.JButton eDeletar;
    private javax.swing.JTextField eEst;
    private javax.swing.JButton eExibir;
    private javax.swing.JButton eIncluir;
    private javax.swing.JButton eLimpar;
    private javax.swing.JTextField eNome;
    private javax.swing.JTextField ePrec;
    private javax.swing.JTextField eQtd;
    private javax.swing.JTable eTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
